project/project/urls.py
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib import admin
from django.urls import path
from analytics import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.main, name="main"),
    path("demand/", views.demand, name="demand"),
    path("geography/", views.geography, name="geography"),
    path("skills/", views.skills, name="skills"),
    path("latest_vacancies/", views.latest_vacancies, name="latest_vacancies"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/analytics/models.py
from django.db import models


class DemandContent(models.Model):
    title = models.CharField(max_length=50)
    content = models.JSONField(null=True)
    load_dttm = models.DateTimeField(auto_now_add=True)
    graphic = models.ImageField(upload_to="images", null=True)

    def __str__(self):
        return self.title


class GeographyContent(models.Model):
    title = models.CharField(max_length=50)
    content = models.JSONField(null=True)
    load_dttm = models.DateTimeField(auto_now_add=True)
    graphic = models.ImageField(upload_to="images", null=True)

    def __str__(self):
        return self.title


class SkillsContent(models.Model):
    title = models.CharField(max_length=50)
    load_dttm = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class SkillsYear(models.Model):
    title = models.CharField(max_length=20)
    content = models.JSONField(null=True)
    load_dttm = models.DateTimeField(auto_now_add=True)
    graphic = models.ImageField(upload_to="images/skills", null=True)
    skills_content = models.ForeignKey(SkillsContent, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

project/analytics/views.py
import asyncio

from django.shortcuts import render
from .models import *
from back.hh_api import get_latest_vacancies_async


def main(request):
    return render(request, "main.html")


def demand(request):
    all_demands = DemandContent.objects.all()
    return render(request, "demand.html", {"all_demands": all_demands})


def geography(request):
    all_geography = GeographyContent.objects.all()
    return render(request, "geography.html", {"all_geography": all_geography})


def skills(request):
    all_skills = SkillsContent.objects.all()
    return render(request, "skills.html", {"all_skills": all_skills})


def latest_vacancies(request):
    return render(request, "latest_vacancies.html", {"vacancies": asyncio.run(get_latest_vacancies_async())})

project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>C/C++</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/demand.css' %}">
    <link rel="stylesheet" href="{% static 'css/geography.css' %}">
    <link rel="stylesheet" href="{% static 'css/skills.css' %}">
    <link rel="stylesheet" href="{% static 'css/latest_vacancies.css' %}">
    <link type="image/png" sizes="16x16" rel="icon" href="{% static 'images/favicon-16x16.png' %}">
    <link type="image/png" sizes="32x32" rel="icon" href="{% static 'images/favicon-32x32.png' %}">
</head>
<body class="page light-theme">
    <header class="page-header">
        <p class="logo">
            <img src="{% static 'images/logo.svg' %}">
        </p>
        <h1>C++ Analytics</h1>
        <button class="theme-button" id="togButton" type="button">Изменить тему</button>
    </header>
    <main>
        <aside class="main-menu">
            <nav>
                <h3>Навигация по сайту</h3>
                <ul class="site-navigation">
                    <li class="site-navigation-item">
                        <img class="icon" src="{% static 'images/main.svg' %}" width="24" height="24">
                        <a href="{% url 'main' %}">Главная</a>
                    </li>
                    <li class="site-navigation-item">
                        <img class="icon" src="{% static 'images/demand.svg' %}" width="24" height="24">
                        <a href="{% url 'demand' %}">Востребованность</a>
                    </li>
                    <li class="site-navigation-item">
                        <img class="icon" src="{% static 'images/geography.svg' %}" width="24" height="24">
                        <a href="{% url 'geography' %}">География</a>
                    </li>
                    <li class="site-navigation-item">
                        <img class="icon" src="{% static 'images/skills.svg' %}" width="24" height="24">
                        <a href="{% url 'skills' %}">Навыки</a>
                    </li>
                    <li class="site-navigation-item">
                        <img class="icon" src="{% static 'images/latest_vacancies.svg' %}" width="24" height="24">
                        <a href="{% url 'latest_vacancies' %}">Последние вакансии</a>
                    </li>
                </ul>
            </nav>
        </aside>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <h4>Кремлев Андрей Викторович, РИ-220931</h4>
    </footer>
    <script type="module">
        var togButton = document.getElementById("togButton");

        darkOn = localStorage.getItem("dark") == "true" ? true : false;
        setTheme();

        function setTheme(){
            localStorage.setItem("dark", darkOn ? "true" : "false");
            if(darkOn){
                document.body.classList.remove("light-theme");
                document.body.classList.add("dark-theme");
            }
            else{
                document.body.classList.remove("dark-theme");
                document.body.classList.add("light-theme");
            }
        }

        var darkOn = false;
        function toggle(){
            darkOn = !darkOn;
            setTheme();
        }

        togButton.addEventListener("click", toggle);
    </script>
</body>
</html>

project/templates/demand.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="hero">
        <h2>Востребованность</h2>
    </section>
    <article class="demand-article">
        <div class="demand-article-content">
            {% for demand in all_demands %}
                <div class="demand-content">
                    <img class="demand-img" src="{{ demand.graphic.url }}">
                    <table class="demand-table">
                        <caption>{{ demand.title }}</caption>
                        <tr>
                            {% for key in demand.content.keys %}
                                <th>{{ key }}</th>
                            {% endfor %}
                        </tr>
                        <tr>
                            {% for value in demand.content.values %}
                                <td>{{ value }}</td>
                            {% endfor %}
                        </tr>
                    </table>
                </div>
            {% endfor %}
        </div>
    </article>
{% endblock %}

project/templates/geography.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="hero">
        <h2>География</h2>
    </section>
    <article class="geography-article">
        <div class="geography-article-content">
            {% for geography in all_geography %}
                <div class="geography-content">
                    <img class="geography-img" src="{{ geography.graphic.url }}">
                    <table class="geography-table">
                        <caption>{{ geography.title }}</caption>
                        <tr>
                            {% for key in geography.content.keys %}
                                <th>{{ key }}</th>
                            {% endfor %}
                        </tr>
                        <tr>
                            {% for value in geography.content.values %}
                                <td>{{ value }}</td>
                            {% endfor %}
                        </tr>
                    </table>
                </div>
            {% endfor %}
        </div>
    </article>
{% endblock %}

project/templates/latest_vacancies.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="hero">
        <h2>Последние вакансии</h2>
    </section>
    <article class="latest_vacancies-article">
        <div class="latest_vacancies-article-content">
            <ul class="vacancy-list">
                {% for vacancy in vacancies %}
                    <li class="vacancy-list-item">
                        <h3>{{ vacancy.name }}</h3>
                        <p><strong>Описание:</strong> {{ vacancy.description }}</p>
                        <p><strong>Ключевые навыки:</strong> {{ vacancy.key_skills }}</p>
                        <p><strong>Компания:</strong> {{ vacancy.company }}</p>
                        <p><strong>Зарплата:</strong> {{ vacancy.salary }}</p>
                        <p><strong>Местоположение:</strong> {{ vacancy.area_name }}</p>
                        <p><strong>Опубликовано:</strong> {{ vacancy.published_at }}</p>
                        <a href="{{ vacancy.url }}"><strong>Ссылка на вакансию</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </article>
{% endblock %}

project/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="hero">
        <h2>Описание профессии</h2>
    </section>
    <article class="main-article">
        <div class="main-article-content">
            <div class="main-article-images">
                <img src="{% static 'images/image2.png' %}">
                <img src="{% static 'images/image1.png' %}">
                <img src="{% static 'images/image3.png' %}">
            </div>
            <h3>Кто такой разработчик на C++ и чем занимается?</h3>
            <p>Если объяснять простыми словами, то разработчик на С++ – это программист, который занимается созданием сложного ПО и высоконагруженных систем.</p>
            <p>C++ – это высокопроизводительный и мощный язык, который используется в разных отраслях: банковские и корпоративные сервисы, разработка видеоигр и игровых движков, операционные и поисковые системы, искусственный интеллект, роботизированные машины и пр.</p>
            <h3>Особенности разработки на языке C++</h3>
            <p>При всех достоинствах C++ — сложный язык с высоким порогом входа.</p>
            <ul>
                <li>
                    <strong>C++ более низкий уровень, чем у большинства современных языков.</strong> Он все еще считается высокоуровневым, то есть отдаленным от «железа» и близким к человеку, но все же сохраняет возможность, например, напрямую работать с памятью. C++ не настолько уходит в человекопонятную абстракцию, как тот же JavaScript. Он может на довольно глубоком уровне работать с аппаратной частью компьютера. Поэтому важно понимать особенности работы «железа».
                </li>
                <li>
                    <strong>В C++ нет автоматизации сборки мусора и других процессов.</strong> Многие вещи, которые в современных языках программирования за разработчика выполняют автоматические процессы, в C++ делаются вручную. Например, та же работа с памятью: в C++ разработчик выделяет память и управляет ей сам, а если ошибется, могут начаться утечки.
                </li>
                <li>
                    <strong>В C++ много специфичных понятий и абстракций.</strong> Например, один из самых знаменитых типов данных языка C, перешедший и в C++, — указатель. Переменные этого типа буквально указывают на какое-то значение в памяти компьютера, и работать с ними нужно несколько иначе, чем с привычными переменными.
                </li>
            </ul>
            <p>C++ совмещает преимущества низко- и высокоуровневых языков программирования.</p>
            <h3>Почему разработчик на C++ — особенный специалист</h3>
            <p>В большинстве других языков программирования разработчику не нужно знать, как работает техническая «начинка»: для сложных процессов есть библиотеки и уже готовые функции. В C++ программист должен понимать, как все устроено. Именно так он может писать эффективный и быстрый код.</p>
            <p>В теории можно работать с C++ как с другими языками и не углубляться в детали, но на практике это бесполезно. Так теряется главный плюс C++ — возможность писать код, оптимизированный под «железо» и потому очень быстрый.</p>
            <p>Хороший разработчик на C++ — человек, который, кроме самого языка программирования, разбирается в устройстве компьютера, алгоритмах и структурах данных, а еще умеет их применять. Для работы с языком важны познания в Computer Science: без них эффективные программы писать не получится.</p>
        </div>
    </article>
{% endblock %}

project/templates/skills.html
{% extends 'base.html' %}
{% load static %}
{% load to_list %}

{% block content %}
    <section class="hero">
        <h2>Навыки</h2>
    </section>
    <article class="skills-article">
        <div class="skills-article-content">
            {% for skills in all_skills %}
                <h3>{{ skills.title }}</h3>
                {% for skills_year in skills.skillsyear_set.all %}
                    <div class="skills-year-content">
                        <img class="skills-year-img" src="{{ skills_year.graphic.url }}">
                        <table class="skills-year-table">
                            <caption>{{ skills_year.title }}</caption>
                            {% with skills_year.content.values|to_list as values %}
                                <tr>
                                    {% for skill in values.0.0 %}
                                        <th>{{ skill }}</th>
                                    {% endfor %}
                                </tr>
                                <tr>
                                    {% for freq in values.0.1 %}
                                        <td>{{ freq }}</td>
                                    {% endfor %}
                                </tr>
                            {% endwith %}
                        </table>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
    </article>
{% endblock %}